version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: devsecops_db
    environment:
      POSTGRES_USER: devsecops
      POSTGRES_PASSWORD: password
      POSTGRES_DB: devsecops_tracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
